# Generated by Django 2.0.4 on 2019-03-17 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.IntegerField(blank=True, default=1, null=True)),
                ('document', models.FileField(upload_to='media/')),
            ],
        ),
    ]
