# Generated by Django 2.0.4 on 2019-03-23 09:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedata',
            name='delete_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 24, 14, 30, 19, 865589)),
        ),
        migrations.AlterField(
            model_name='filedata',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 23, 14, 30, 19, 865472)),
        ),
    ]
