# Generated by Django 2.0.4 on 2019-03-17 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileaddress',
            name='token',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='file_data', to='uploader.FileData'),
            preserve_default=False,
        ),
    ]
