# Generated by Django 2.0.4 on 2019-03-20 20:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0003_auto_20190320_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='filedata',
            name='delete_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='filedata',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 21, 1, 57, 29, 23728)),
        ),
    ]
