# Generated by Django 2.0.4 on 2019-03-21 09:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0004_auto_20190321_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedata',
            name='delete_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 22, 14, 50, 3, 237357)),
        ),
        migrations.AlterField(
            model_name='filedata',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 21, 14, 50, 3, 237236)),
        ),
    ]
