# Generated by Django 2.0.4 on 2019-07-27 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IcanuploadUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),  # NOQA
                ('password', models.CharField(max_length=128, verbose_name='password')),  # NOQA
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),  # NOQA
                ('email', models.EmailField(db_index=True, max_length=255, unique=True)),  # NOQA
                ('username', models.CharField(db_index=True, max_length=255, unique=True)),  # NOQA
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('profile_image', models.FileField(blank=True, null=True, upload_to='authuser/profile')),  # NOQA
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_email_varified', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
